---
title: "Construcción de un diagrama de flujo"
author: "Gerardo Martín"
fontsize: 11pt
output:
  beamer_presentation:
    theme: metropolis
    highlight: pygments
    slide_level: 3
    fig_height: 4.5
    fig_caption: true
    latex_engine: xelatex
    keep_tex: true
date: '2022-06-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf')
```

### Razones

- Identificar necesidades

    - Materiales
    - Espacio físico
    - Fechas de inicio
    - Fechas de toma de muestra
    - Fechas de fin
    - Identificación de estrategia de análisis
    - Estructuración de base de datos
    
### Técnicas

1. Determinar objetivo, hipótesis o pregunta de investigación
2. Identificar factores que se pueden manipular
3. Identificar maneras de manipular factores experimentalmente ó geográficamente (estudios observacionales)
4. Determinar necesidades de espacio
5. Hacer lista de materiales
6. Hacer diagrama de diseño

# Ejemplo

### El experimento

[Influencia de tres regímenes de riego](https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0187-57792022000100110&lang=es)

[Diagrama de flujo](Figuras-disenos/diagrama.odg)

# El proyecto de análisis

### ¿Qué variable(s) de respuesta habrá?

En cosecha:

1. Altura de la planta
2. Número de espigas

Depués de cosecha:

1. Tamaño de espiga
2. Número de granos en la espiga
3. Color de los granos
4. Peso de 1000 granos
5. Rendimiento
6. Cantidad de proteína y ceniza

### ¿Qué variable(s) independientes habrá?

1. Tres regímenes de humedad del suelo, con valores:

    - Lámina de riego de 39.3 cm
    - Control con lámina de 42.5 cm
    - Lámina de riego de 44.8 cm
    
### Modelo de análisis

Comparación de medias:

1. ANOVA ó ANODE
2. Regresión lineal

Ejemplo NOVA:

$$ Peso(Regimen) =  \alpha + \beta_{Regimen} $$

- $\alpha =$ Promedio global de $Peso$
- $\beta_{Regímen} =$ Diferencia entre $\alpha$ y peso promedio de cada tratamiento

### Modelo de análisis

Ejemplo de regresión lineal:

$$ Peso(Lamina) = \alpha + \beta \times Lamina $$

- $\alpha =$ Intercepto, valor de $Peso$ cuando $Lamina = 0$
- $\beta =$ Pendiente, cuańto cambia el peso cuando $Lamina$ aumenta en 1 unidad

### Análisis multivariado

